language: python
python:
  - "2.7.6"
# Install dependencies
install: "pip install -r requirements/local.txt"

# run tests
script: python manage.py test

# environment variables
env:
  - SECRET_KEY="1$lno6!(tqxv22!jl*9s(dgpov__(_4gh%_4j(78891r($v@h3"
  - DATABASE_URL=postgres://postgres:@127.0.0.1:5432/travis_test

# db stuff
services:
  - postgresql

# initialization
before_script:
  - psql -c 'create database travis_test;' -U postgres
  - psql -c "create role ubuntu with login createdb password 'pAssw0rd';" -U postgres
  - psql -U postgres -d travis_test < circleci_db.sql

# sudo: required
